[build]
  command = "npm run build"
  publish = "out"
  functions = "functions"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "out"

package = "@netlify/plugin-nextjs"

[[redirects]]
    from = "/api/*"
    to= "/.netlify/functions/:splat"
    status = 200